name: chuck_normis_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  dynamic_color: ^1.8.1
  collection: ^1.17.0
  sqflite: ^2.4.2
  path: ^1.9.1
  audioplayers: ^6.5.1
  image_picker: ^1.2.0
  web_socket_channel: ^3.0.3
  xml: ^6.6.1
  vosk_flutter:
    git:
      url: https://github.com/alphacep/vosk-flutter.git
      ref: master
  path_provider: ^2.0.11
  archive: ^3.3.0
  provider: ^6.1.5+1
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2

      
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/sounds/start.mp3
    - assets/sounds/finish.mp3
    - assets/sounds/bell-in-the-boxing-ring.mp3
    - assets/sounds/door-knock-solid-door.mp3
    - assets/sounds/short-ringing-notification-sound.mp3
    - assets/models/
    - assets/icon/icon_nav.webp

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

